// Action Type Constants
export const actionTypes = {
  FETCH_CATEGORY_REQUEST: "FETCH_CATEGORY_REQUEST",
  FETCH_CATEGORY_SUCCESS: "FETCH_CATEGORY_SUCCESS",
  FETCH_CATEGORY_FAILURE: "FETCH_CATEGORY_FAILURE",
  FETCH_POST_REQUEST: "FETCH_POST_REQUEST",
  FETCH_POST_SUCCESS: "FETCH_POST_SUCCESS",
  FETCH_POST_FAILURE: "FETCH_POST_FAILURE",
  NEW_POST: "NEW_POST",
  VOTE_POST: "VOTE_POST",
  EDIT_POST: "EDIT_POST",
  DELETE_POST: "DELETE_POST",
  FETCH_COMMENT_REQUEST: "FETCH_COMMENT_REQUEST",
  FETCH_COMMENT_SUCCESS: "FETCH_COMMENT_SUCCESS",
  FETCH_COMMENT_FAILURE: "FETCH_COMMENT_FAILURE",
  NEW_COMMENT: "NEW_COMMENT",
  VOTE_COMMENT: "VOTE_COMMENT",
  EDIT_COMMENT: "EDIT_COMMENT",
  DELETE_COMMENT: "DELETE_COMMENT"
};
